jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Afsy\Bundle\CoreBundle\Entity\Author: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        entity:
            entity: { class: AfsyCoreBundle:Author, property: email }

    firewalls:
        secured_area:
            pattern:        ^/
            logout:         ~
            anonymous:      true
            oauth:
                resource_owners:
                    sensio_connect: "/login/check-connect"
                login_path:     /login
                failure_path:   /login

                oauth_user_provider:
                    service: afsy.oauth.author.provider

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_USER }
        - { path: ^/blog/preview/, role: ROLE_USER }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
